import type { ColumnInfo } from "@/lib/introspection";

export type InputKind =
  | "checkbox"
  | "number"
  | "date"
  | "datetime-local"
  | "select"
  | "textarea"
  | "text";

export function isAutoGenerated(column: ColumnInfo): boolean {
  return column.extra.toLowerCase().includes("auto_increment");
}

/** columnType（例: enum('A','B')）から選択肢を取り出す。 */
export function parseEnumOptions(columnType: string): string[] {
  const match = columnType.match(/^enum\((.*)\)$/i);
  if (!match) return [];
  return match[1]
    .split(",")
    .map((raw) => raw.trim().replace(/^'/, "").replace(/'$/, "").replace(/''/g, "'"));
}

export function inputKindFor(column: ColumnInfo): InputKind {
  const columnType = column.columnType.toLowerCase();
  if (columnType === "tinyint(1)") return "checkbox";
  if (/^enum\(/.test(columnType)) return "select";
  if (/^(int|bigint|smallint|mediumint|tinyint|decimal|float|double)/.test(column.dataType)) {
    return "number";
  }
  if (column.dataType === "date") return "date";
  if (column.dataType === "datetime" || column.dataType === "timestamp") return "datetime-local";
  if (["text", "longtext", "mediumtext", "tinytext"].includes(column.dataType)) return "textarea";
  return "text";
}

// 対象プール（createTargetPool）は dateStrings: true なので、DATE / DATETIME / TIMESTAMP は
// DBが返した文字列（`YYYY-MM-DD` / `YYYY-MM-DD HH:MM:SS[.ffffff]`）のまま届く。Date を経由すると
// プロセスのTZで解釈されて値がずれるため、ここでは文字列の区切りを変えるだけにする。
const DATETIME_PATTERN = /^(\d{4}-\d{2}-\d{2})[T ](\d{2}:\d{2})(:\d{2}(?:\.\d+)?)?$/;
const ZERO_DATE_PATTERN = /^0000-00-00/;

/** DBの日時文字列（`YYYY-MM-DD HH:MM:SS`）を datetime-local の value（`T` 区切り）へ変換する。 */
export function toDateTimeInputValue(value: string): string {
  if (ZERO_DATE_PATTERN.test(value)) return "";
  const match = value.match(DATETIME_PATTERN);
  if (!match) return value;
  return `${match[1]}T${match[2]}${match[3] ?? ":00"}`;
}

/**
 * datetime-local の入力値をDBへ書き込む形（`YYYY-MM-DD HH:MM:SS`）へ変換する。
 * ブラウザは秒が 0 のとき秒を省いた値（`YYYY-MM-DDTHH:MM`）を送るため、ここで `:00` を補う。
 */
export function toDatabaseDateTime(value: string): string {
  const match = value.match(DATETIME_PATTERN);
  if (!match) return value;
  return `${match[1]} ${match[2]}${match[3] ?? ":00"}`;
}

/** datetime-local の step 属性。秒までを持つカラムは "1"、DATETIME(3) のような小数秒つきはその刻みにする。 */
export function dateTimeStepFor(columnType: string): string {
  const precision = Number(columnType.match(/\((\d+)\)/)?.[1] ?? 0);
  return precision > 0 ? `0.${"0".repeat(precision - 1)}1` : "1";
}

/** DBから取得した値をHTMLフォームの value 属性用文字列に変換する。 */
export function formatValueForInput(value: unknown, kind: InputKind): string {
  if (value === null || value === undefined) return "";
  if (kind === "checkbox") return value ? "1" : "";
  if (kind === "date") {
    const text = String(value);
    return ZERO_DATE_PATTERN.test(text) ? "" : text;
  }
  if (kind === "datetime-local") return toDateTimeInputValue(String(value));
  if (Buffer.isBuffer(value)) return `0x${value.toString("hex")}`;
  if (typeof value === "object") return JSON.stringify(value);
  return String(value);
}

/**
 * 差分の判定用に、ブラウザの送信時の癖をそろえる。textarea は改行を CRLF へ正規化して送り、
 * datetime-local は秒が 0 のとき秒を省いて送る。
 */
function normalizeForCompare(text: string, kind: InputKind): string {
  if (kind === "textarea") return text.replace(/\r\n/g, "\n");
  if (kind === "datetime-local") return toDatabaseDateTime(text);
  return text;
}

/**
 * フォームの入力値からDB書き込み用のデータオブジェクトを組み立てる。
 * auto_increment カラムは常に除外する。NOT NULLで空欄のカラムはキー自体を含めない
 * （INSERTではDBのDEFAULTに委ね、UPDATEでは値を変更しない）。
 *
 * `currentRow`（UPDATEの対象行の現在値）を渡すと、フォームの値がそれと同じカラムは
 * 結果に含めない。UPDATEが全カラムを書き戻すと、フォームで表現しきれない値（DATETIMEの
 * 小数秒・表示できない日付など）を、触っていないカラムまで変えてしまうため。
 */
export function buildRowDataFromForm(
  formData: FormData,
  columns: ColumnInfo[],
  currentRow?: Record<string, unknown>,
): Record<string, unknown> {
  const data: Record<string, unknown> = {};

  for (const column of columns) {
    if (isAutoGenerated(column)) continue;

    const kind = inputKindFor(column);
    const current = currentRow ? currentRow[column.name] : undefined;

    if (kind === "checkbox") {
      const checked = formData.get(column.name) === "on";
      if (currentRow && checked === Boolean(current)) continue;
      data[column.name] = checked ? 1 : 0;
      continue;
    }

    const raw = formData.get(column.name);
    const text = typeof raw === "string" ? raw : "";
    if (
      currentRow &&
      normalizeForCompare(text, kind) ===
        normalizeForCompare(formatValueForInput(current, kind), kind)
    ) {
      continue;
    }

    const value = text.trim();
    if (value === "") {
      if (column.isNullable) {
        data[column.name] = null;
      }
      continue;
    }
    data[column.name] = kind === "datetime-local" ? toDatabaseDateTime(value) : value;
  }

  return data;
}
