import type { ColumnInfo } from "@/lib/introspection";

export type InputKind =
  | "checkbox"
  | "number"
  | "date"
  | "datetime-local"
  | "select"
  | "textarea"
  | "text";

export function isAutoGenerated(column: ColumnInfo): boolean {
  return column.extra.toLowerCase().includes("auto_increment");
}

/** columnType（例: enum('A','B')）から選択肢を取り出す。 */
export function parseEnumOptions(columnType: string): string[] {
  const match = columnType.match(/^enum\((.*)\)$/i);
  if (!match) return [];
  return match[1]
    .split(",")
    .map((raw) => raw.trim().replace(/^'/, "").replace(/'$/, "").replace(/''/g, "'"));
}

export function inputKindFor(column: ColumnInfo): InputKind {
  const columnType = column.columnType.toLowerCase();
  if (columnType === "tinyint(1)") return "checkbox";
  if (/^enum\(/.test(columnType)) return "select";
  if (/^(int|bigint|smallint|mediumint|tinyint|decimal|float|double)/.test(column.dataType)) {
    return "number";
  }
  if (column.dataType === "date") return "date";
  if (column.dataType === "datetime" || column.dataType === "timestamp") return "datetime-local";
  if (["text", "longtext", "mediumtext", "tinytext"].includes(column.dataType)) return "textarea";
  return "text";
}

function toDate(value: unknown): Date | null {
  if (value instanceof Date) return value;
  if (typeof value === "string" || typeof value === "number") {
    const date = new Date(value);
    return Number.isNaN(date.getTime()) ? null : date;
  }
  return null;
}

/** DBから取得した値をHTMLフォームの value 属性用文字列に変換する。 */
export function formatValueForInput(value: unknown, kind: InputKind): string {
  if (value === null || value === undefined) return "";
  if (kind === "checkbox") return value ? "1" : "";
  if (kind === "date") {
    const date = toDate(value);
    return date ? date.toISOString().slice(0, 10) : String(value);
  }
  if (kind === "datetime-local") {
    const date = toDate(value);
    return date ? date.toISOString().slice(0, 16) : String(value);
  }
  if (Buffer.isBuffer(value)) return `0x${value.toString("hex")}`;
  if (typeof value === "object") return JSON.stringify(value);
  return String(value);
}

/**
 * フォームの入力値からDB書き込み用のデータオブジェクトを組み立てる。
 * auto_increment カラムは常に除外する。NOT NULLで空欄のカラムはキー自体を含めない
 * （INSERTではDBのDEFAULTに委ね、UPDATEでは値を変更しない）。
 */
export function buildRowDataFromForm(
  formData: FormData,
  columns: ColumnInfo[],
): Record<string, unknown> {
  const data: Record<string, unknown> = {};

  for (const column of columns) {
    if (isAutoGenerated(column)) continue;

    const kind = inputKindFor(column);
    if (kind === "checkbox") {
      data[column.name] = formData.get(column.name) === "on" ? 1 : 0;
      continue;
    }

    const raw = formData.get(column.name);
    const value = typeof raw === "string" ? raw.trim() : "";
    if (value === "") {
      if (column.isNullable) {
        data[column.name] = null;
      }
      continue;
    }
    data[column.name] = value;
  }

  return data;
}
