-- AlterTable
ALTER TABLE `AuditLog` MODIFY `action` ENUM('ROW_INSERT', 'ROW_UPDATE', 'ROW_DELETE', 'TABLE_CREATE', 'TABLE_ALTER', 'TABLE_DROP', 'TABLE_TRUNCATE', 'COLUMN_ADD', 'COLUMN_ALTER', 'COLUMN_DROP', 'INDEX_ADD', 'INDEX_DROP', 'SQL_EXECUTE', 'MANAGED_DB_CREATE', 'MANAGED_DB_UPDATE', 'MANAGED_DB_DELETE') NOT NULL;

-- CreateTable
CREATE TABLE `ManagedDatabase` (
    `id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `label` VARCHAR(191) NOT NULL,
    `mode` ENUM('READ_ONLY', 'DATA_WRITE', 'SCHEMA_WRITE') NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `ManagedDatabase_name_key`(`name`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
