import type { ColumnInfo } from "@/lib/introspection";
import {
  formatValueForInput,
  inputKindFor,
  isAutoGenerated,
  parseEnumOptions,
} from "@/lib/row-form";

export function RowFormFields({
  columns,
  initialValues,
}: {
  columns: ColumnInfo[];
  initialValues?: Record<string, unknown>;
}) {
  return (
    <>
      {columns.map((column) => {
        if (isAutoGenerated(column)) return null;

        const kind = inputKindFor(column);
        const initial = initialValues ? initialValues[column.name] : undefined;
        const required = !column.isNullable && column.columnDefault === null;
        const defaultValue = formatValueForInput(initial, kind);

        return (
          <label key={column.name} className="flex flex-col gap-1 text-sm">
            <span className="flex flex-wrap items-center gap-x-2 gap-y-0.5">
              <span className="font-medium">{column.name}</span>
              <span className="text-muted-foreground min-w-0 text-xs break-all">
                {column.columnType}
                {required ? "・必須" : ""}
              </span>
            </span>

            {kind === "checkbox" ? (
              <input
                type="checkbox"
                name={column.name}
                defaultChecked={!!initial}
                className="h-4 w-4"
              />
            ) : kind === "select" ? (
              <select
                name={column.name}
                defaultValue={defaultValue}
                required={required}
                className="rounded-md border px-3 py-2"
              >
                {!required && <option value="">(NULL)</option>}
                {parseEnumOptions(column.columnType).map((option) => (
                  <option key={option} value={option}>
                    {option}
                  </option>
                ))}
              </select>
            ) : kind === "textarea" ? (
              <textarea
                name={column.name}
                defaultValue={defaultValue}
                required={required}
                rows={3}
                className="rounded-md border px-3 py-2"
              />
            ) : (
              <input
                type={kind}
                name={column.name}
                defaultValue={defaultValue}
                required={required}
                step={kind === "number" ? "any" : undefined}
                className="rounded-md border px-3 py-2"
              />
            )}
          </label>
        );
      })}
    </>
  );
}
